### ISSUE TITLE
Can I add project on web base password manager?

### ISSUE THREAD

**Issue by coderj001** [sudhanshutiwari264/Python-Projects-for-Intermediates#2]

**Comment by sudhanshutiwari264** [comment]
@coderj001 yaa sure go ahead !

**Comment by sudhanshutiwari264** [comment]
Hey @coderj001 !
I hope you are doing great !
Just wants to know are you still working on this ?

**Comment by coderj001** [comment]
Yes, sorry for the delay.

**Comment by sudhanshutiwari264** [comment]
@coderj001 No problem 😅 ,just take your time 🙌!
👍
